FROM node:latest

WORKDIR /app

ARG NEXT_PUBLIC_RUN_MODE
ARG NEXT_PUBLIC_API_URL_DEV
ARG NEXT_PUBLIC_API_URL_PROD
ARG NEXT_PUBLIC_TOKEN_KEY
ARG SITE_URL
ARG NEXT_PUBLIC_MEASUREMENT_ID

ENV NEXT_PUBLIC_RUN_MODE=$NEXT_PUBLIC_RUN_MODE
ENV NEXT_PUBLIC_API_URL_DEV=$NEXT_PUBLIC_API_URL_DEV
ENV NEXT_PUBLIC_API_URL_PROD=$NEXT_PUBLIC_API_URL_PROD
ENV NEXT_PUBLIC_TOKEN_KEY=$NEXT_PUBLIC_TOKEN_KEY
ENV NEXT_PUBLIC_MEASUREMENT_ID=$NEXT_PUBLIC_MEASUREMENT_ID
ENV SITE_URL=$SITE_URL

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
