name: CI/CD - CitaCheck Frontend Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/citacheck-fe:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/citacheck-fe:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_RUN_MODE=production
            NEXT_PUBLIC_API_URL_DEV=${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
            NEXT_PUBLIC_API_URL_PROD=${{ secrets.NEXT_PUBLIC_API_URL_PROD }}
            NEXT_PUBLIC_TOKEN_KEY=${{ secrets.NEXT_PUBLIC_TOKEN_KEY }}
            SITE_URL=${{ secrets.SITE_URL }}
            NEXT_PUBLIC_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_MEASUREMENT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Setup OpenVPN connection
        run: |
          printf "%s\n%s" "${{ secrets.OPENVPN_USERNAME }}" "${{ secrets.OPENVPN_PASSWORD }}" > vpn-auth.txt
          chmod 600 vpn-auth.txt
          echo "${{ secrets.OPENVPN_CONFIG_B64 }}" | base64 -d > vpn.ovpn
          sudo openvpn --config vpn.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 10
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | sudo docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            cd /var/www/citacheck-frontend
            sudo docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/citacheck-fe:latest
            sudo docker compose -f docker-compose.yml down --remove-orphans
            sudo docker compose -f docker-compose.yml up -d
            sudo docker image prune -f
